server:
  port: 8085

spring:
  cloud:
    gateway:
      routes:
        - id: cofetarie-service-root
          uri: http://localhost:8080
          predicates:
            - Path=/cofetarie
          filters:
            - RewritePath=/cofetarie, /cofetarie-service/cofetarie

        - id: cofetarie-service-with-id
          uri: http://localhost:8080
          predicates:
            - Path=/cofetarie/**
          filters:
            - RewritePath=/cofetarie/(?<remaining>.*), /cofetarie-service/cofetarie/${remaining}

      globalcors:
          corsConfigurations:
            '[/**]':
              allowedOrigins:
                - "http://localhost:3000"
              allowedMethods:
                - GET
                - POST
                - PUT
                - DELETE
                - OPTIONS
              allowedHeaders:
                - "*"
              allowCredentials: true